spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/memora_db}
    username: ${DB_USERNAME:memora_admin}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        highlight_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  scheduling:
    default-timezone: Asia/Seoul

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}
  client-secret: ${KAKAO_CLIENT_SECRET}

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 31536000000    # 1년
  refresh-token-validity: 31536000000   # 1년

openrouter:
  api-key: ${OPENROUTER_API_KEY}
  endpoint: https://openrouter.ai/api/v1/chat/completions
  model: openai/gpt-4o